// Generated by CoffeeScript 1.6.3
(function() {
  var allowedFilenames, compileJadeFile, data, destinationDir, fs, handeWatch, jade, renderFile, renderOrWalk, resolveCompiledPath, resultExtenstion, spawn, walkAndRender, watchDir;

  fs = require('fs');

  jade = require('jade');

  spawn = require('child_process').spawn;

  allowedFilenames = new RegExp('^.*\.jade$');

  watchDir = '/';

  destinationDir = '/';

  data = {};

  resultExtenstion = 'html';

  module.exports = function(currentDir, target, destDir, dataFile, resExt) {
    data = require(currentDir + '/' + dataFile);
    watchDir = currentDir + '/' + target;
    destinationDir = destDir ? currentDir + '/' + destDir : watchDir;
    resultExtenstion = '.' + (resExt ? resExt : resultExtenstion);
    console.log('Start watching', watchDir);
    console.log('Render to ', destinationDir);
    console.log('With extension ', resultExtenstion);
    walkAndRender(watchDir);
    return fs.watch(watchDir, handeWatch);
  };

  walkAndRender = function(dir) {
    return fs.readdir(dir, function(err, list) {
      var file, filename, listLength, _i, _len, _results;
      if (err) {
        throw new Error(err);
      }
      listLength = list.length;
      if (!listLength) {
        return null;
      }
      _results = [];
      for (_i = 0, _len = list.length; _i < _len; _i++) {
        file = list[_i];
        filename = dir + '/' + file;
        _results.push(renderOrWalk(filename));
      }
      return _results;
    });
  };

  renderOrWalk = function(filename) {
    return fs.stat(filename, function(err, stat) {
      if (err) {
        throw new Error(err);
      }
      if (stat && stat.isDirectory()) {
        return walkAndRender(filename);
      } else {
        return renderFile(filename);
      }
    });
  };

  handeWatch = function(event, filename) {
    if (!allowedFilenames.test(filename)) {
      return false;
    }
    return renderFile(watchDir + '/' + filename);
  };

  resolveCompiledPath = function(filename, domain) {
    var fileDir;
    filename = filename.replace(/\.jade$/, resultExtenstion);
    filename = filename.replace(watchDir, '');
    filename = filename.replace(/^\/*/, '');
    filename = filename.split('/').join('-');
    if (domain) {
      fileDir = [destinationDir, domain].join('/');
      if (!fs.existsSync(fileDir)) {
        fs.mkdirSync(fileDir);
      }
      filename = [fileDir, filename].join('/');
    } else {
      filename = [destinationDir, filename].join('/');
    }
    return filename;
  };

  renderFile = function(filename) {
    var domain, _ref, _results;
    _ref = data.domains;
    _results = [];
    for (domain in _ref) {
      data = _ref[domain];
      console.log(filename, domain, data);
      _results.push(compileJadeFile(filename, domain, data));
    }
    return _results;
  };

  compileJadeFile = function(filename, domain, data) {
    data = data || {};
    return jade.renderFile(filename, data, function(err, html) {
      var compiledPath;
      if (err) {
        return console.log(err);
      }
      compiledPath = resolveCompiledPath(filename, domain);
      return fs.writeFile(compiledPath, html, function(err) {
        if (err) {
          return console.log(err);
        }
        return console.log(compiledPath, ' compiled.');
      });
    });
  };

}).call(this);
